### ISSUE TITLE
Can't Connect

### ISSUE THREAD

**Issue by tqvunguyen** [toscano/hass-avpro-acmxnn#1]
Hi,
I have an AC-MX-82RM. After installing, when I enter my IP address or hostname, I get "Failed to connect". I'm hoping you can help with this last step of this integration.

**Comment by toscano** [comment]
Hi @tqvunguyen thanks for reporting. Two questions...

1. Can you open the switches web page in a browser? Are you prompted for a password? 
2. Could you enable logging for the addin and retry then postthose logs here?

Thanks

**Comment by tqvunguyen** [comment]
Hi @toscano,
Thank you for getting back to me. 

1. I can log into the switch through the web browser. I attempted with enable web interface passwords and without and still connect to HA.
2. I'm unsure if this is the right log you are requesting. I have attached an image of my switch network settings if there is anything I need to change. 

This error originated from a custom integration.
Logger: custom_components.avpro-acmxnn
Source: custom_components/avpro-acmxnn/config_flow.py:42
integration: AC-MX Matrix switch (documentation, issues)
First occurred: 7:49:35 PM (3 occurrences)
Last logged: 7:49:49 PM

Cannot connect

![AVPro](https://github.com/toscano/hass-avpro-acmxnn/assets/104610902/c2d5b73f-b1b4-4d4d-b9ef-7a3343677abe)

**Comment by toscano** [comment]
I was hoping to get a copy of your HomeAssistant.log file. You can learn more about that here https://www.home-assistant.io/integrations/logger/

**Comment by tqvunguyen** [comment]
Thank you for the link.
Here is what it shows on the log. 

2024-06-10 08:32:03.729 DEBUG (MainThread) [custom_components.avpro-acmxnn] Testing connection to 192.168.20.232.
2024-06-10 08:32:03.743 INFO (MainThread) [custom_components.avpro-acmxnn] Found matrix switch named 'AC-MX-82' of model '' with mac address '18:8a:6a:02:18:1d' and serial number '' on 192.168.20.232:23.
2024-06-10 08:32:03.744 WARNING (MainThread) [custom_components.avpro-acmxnn] Description request to 192.168.20.232 failed.
2024-06-10 08:32:03.744 ERROR (MainThread) [custom_components.avpro-acmxnn] Cannot connect

**Comment by toscano** [comment]
Thank you this is exactly what I needed. 

Seems like your device doesn't support web sockets. It's okay if you don't understand what that means. There is another way to communicate which I can add to the integration. It'll take me a little while since I'm on vacation this week. Give me until next week and I'll let you know when I have an update to try.

**Comment by toscano** [comment]
@tqvunguyen ,

Can you look at [this](https://avproglobal.egnyte.com/dl/CoLLLWoDlf) online user guide and verify...

 * `Page 18` - Admin Web Interface is ***NOT*** set as Secure.
 * `Page 19` - User Web Interface is ***NOT*** set as Secure.
 * `Page 25` - Console works as described in the user guide.

I'm still away on vacation but this info will help going forward.

**Comment by tqvunguyen** [comment]
Hi,

Thank you for sending over this link. I have tried using both Admin and User Secure and other combinations. 

Please take the time and enjoy your vacation. I don't mind waiting.

**Comment by toscano** [comment]
@tqvunguyen 

After getting home from vacation I think that I've stumbled on to your issue. I need one more thing from you to confirm.

Please use your web browser to visit `http://IP_OF_YOUR_MATRIX/do?cmd=status` and post the raw data of the result here.
It should look something like this:

```json
{
 "info":{
   "websecure":false
   ,"webpassword":""
   ,"rs232telnetsecure":false

   // OMITTED FOR BREVITY

}}
```

Thanks again for your patience.

**Comment by tqvunguyen** [comment]
@toscano ,

I hope you enjoy your vacation! I have here the information that you asked for. 

{"info":
	{"websecure":false,
	"webpassword":"",
	"rs232telnetsecure":false,
	"adminpassword":"",
	"mac":"18:8a:6a:02:18:1d",
	"rs232telnetpassword":"",
	"webuser":"",
	"rs232telnet":1,
	"deviceAccessKey":"",
	"hardver":"0.10",
	"usb0":"static/192.168.36.119/255.255.255.0",
	"serialnumber":"",
	"devicemac":"18:8a:6a:02:18:1d",
	"last_updated":"",
	"mcuVersion":"",
	"adminsecure":1,
	"rs232telnetuser":"",
	"usersecure":1,
	"userusername":"user",
	"betaupdatechannel":false,
	"cloudEnable":1,
	"syncproPartnerID":"2f3e4d04-be6a-45a7-b413-973475c1d748",
	"privacyStatus":1,
	"dns":"1.1.1.1 8.8.8.8 192.168.20.1",
	"virtualnumber":"",
	"syncproHost":"https://hub.syncpro.io/v1/devices",
	"eth0":"dhcp",
	"userpassword":"",
	"modelname":"",
	"name":"",
	"rs232telnetport":23,
	"EULAStatus":1,
	"portalias":"",
	"syncproModelID":"ad9e18bc-9195-448f-936b-c3d85438112a",
	"syncproEnable":false,
	"softver":"1.05",
	"deviceID":"",
	"config_version":1,
	"adminusername":"admin"
	}
}

**Comment by toscano** [comment]
@tqvunguyen Thanks for the fast reply.

**This is VERY INTERESTING...**

```json
"modelname":""
```
Should NOT be empty. In your case it should be something like `AC-MX-82`. And

```json
"portalias":""
```

Should also not be empty. This SHOULD have an array of input and output names such as the one my AX-MX-44-B reports
```json

"portalias": {"inputsID":[{"port":"IN 1","id":"AppleTV"},{"port":"IN 2","id":"Blu-ray"},{"port":"IN 3","id":"Shield"},{"port":"IN 4","id":"PreRoll"},{"port":"IN 5","id":""},{"port":"IN 6","id":""},{"port":"IN 7","id":""},{"port":"IN 8","id":""},{"port":"IN 9","id":""},{"port":"IN 10","id":""},{"port":"IN 11","id":""},{"port":"IN 12","id":""},{"port":"IN 13","id":""},{"port":"IN 14","id":""},{"port":"IN 15","id":""},{"port":"IN 16","id":""}],"outputsVideoID":[{"port":"OUT 1","id":"MadVR"},{"port":"OUT 2","id":"Anthem"},{"port":"OUT 3","id":"Lounge"},{"port":"OUT 4","id":".OUT 4"},{"port":"OUT 5","id":""},{"port":"OUT 6","id":""},{"port":"OUT 7","id":""},{"port":"OUT 8","id":""},{"port":"OUT 9","id":""},{"port":"OUT 10","id":""},{"port":"OUT 11","id":""},{"port":"OUT 12","id":""},{"port":"OUT 13","id":""},{"port":"OUT 14","id":""},{"port":"OUT 15","id":""},{"port":"OUT 16","id":""}],"outputsAudioID":[{"port":"OUT 1","id":""},{"port":"OUT 2","id":""},{"port":"OUT 3","id":""},{"port":"OUT 4","id":""},{"port":"OUT 5","id":""},{"port":"OUT 6","id":""},{"port":"OUT 7","id":""},{"port":"OUT 8","id":""},{"port":"OUT 9","id":""},{"port":"OUT 10","id":""},{"port":"OUT 11","id":""},{"port":"OUT 12","id":""},{"port":"OUT 13","id":""},{"port":"OUT 14","id":""},{"port":"OUT 15","id":""},{"port":"OUT 16","id":""}]}
```

I'm not sure why your device isn't reporting this correctly. I would try each of the following steps in order. Test the values again between each step. If you get different (non-blank) values then please re-post the results to this thread.

1. Power off the matrix for 30 seconds then power it back on.
2. Check if there is a firmware update and apply it if there is.
3. Perform a factory reset on the matrix (This will loose your settings so do this only if you're confident that you know how to reconfigure the device.)

**Comment by tqvunguyen** [comment]
Hi,
I did the following

1. Power off the matrix for 30 seconds then power it back on.
          Same as I previously sent you,
2. Check if there is a firmware update and apply it if there is.
          It is up-to-date
3.Perform a factory reset on the matrix (This will loose your settings so do this only if you're confident that you know how to reconfigure the device.)
         Did a factory reset. Here is the new information

{
  "info": {
    "websecure": false,
    "webpassword": "",
    "rs232telnetsecure": false,
    "adminpassword": "admin",
    "mac": "18:8a:6a:02:18:1d",
    "rs232telnetpassword": "",
    "webuser": "",
    "rs232telnet": 1,
    "deviceAccessKey": "",
    "hardver": "0.10",
    "usb0": "static/192.168.36.119/255.255.255.0",
    "serialnumber": "",
    "devicemac": "18:8a:6a:02:18:1d",
    "last_updated": "",
    "mcuVersion": "",
    "adminsecure": false,
    "rs232telnetuser": "",
    "usersecure": false,
    "userusername": "user",
    "betaupdatechannel": false,
    "cloudEnable": false,
    "syncproPartnerID": "2f3e4d04-be6a-45a7-b413-973475c1d748",
    "privacyStatus": false,
    "dns": "1.1.1.1 8.8.8.8 192.168.20.1",
    "virtualnumber": "",
    "syncproHost": "https://hub.syncpro.io/v1/devices",
    "eth0": "dhcp",
    "userpassword": "user123",
    "modelname": "",
    "name": "AC-MX-82RM",
    "rs232telnetport": 23,
    "EULAStatus": false,
    "portalias": "{\"inputsID\":[{\"port\":\"IN 1\",\"id\":\"NSwitch\"},{\"port\":\"IN 2\",\"id\":\"FireTV\"},{\"port\":\"IN 3\",\"id\":\"Chromecast\"},{\"port\":\"IN 4\",\"id\":\"BlueRay\"},{\"port\":\"IN 5\",\"id\":\"Karaoke\"},{\"port\":\"IN 6\",\"id\":\"Playstation\"},{\"port\":\"IN 7\",\"id\":\"\"},{\"port\":\"IN 8\",\"id\":\"\"}],\"outputsVideoID\":[{\"port\":\"OUT 1\",\"id\":\"\"},{\"port\":\"OUT 2\",\"id\":\"\"}],\"outputsAudioID\":[{\"port\":\"OUT 1\",\"id\":\"\"},{\"port\":\"OUT 2\",\"id\":\"\"}]}",
    "syncproModelID": "ad9e18bc-9195-448f-936b-c3d85438112a",
    "syncproEnable": false,
    "softver": "1.05",
    "deviceID": "",
    "config_version": 1,
    "adminusername": "admin"
  }
}

**Comment by toscano** [comment]
Excellent Glad that worked. I'll have more information for you shortly.

**Comment by toscano** [comment]
@tqvunguyen Now that the proper `portalias` is being responded, you should be able to use the custom component without any changes. Please let me know how that goes.

**Comment by tqvunguyen** [comment]
@toscano I'm still getting failed to connect

2024-06-17 14:21:58.609 DEBUG (MainThread) [custom_components.avpro-acmxnn] Testing connection to http://192.168.20.232.
2024-06-17 14:22:02.335 WARNING (MainThread) [custom_components.avpro-acmxnn] Description request to http://192.168.20.232 failed.
2024-06-17 14:22:02.336 ERROR (MainThread) [custom_components.avpro-acmxnn] Cannot connect


EDIT:
It works!!! Thank you so much I didn't name my audio settings. Once again thank you so much

**Comment by toscano** [comment]
Try removing the device and re adding it

**Comment by toscano** [comment]
> 
> EDIT: It works!!! Thank you so much I didn't name my audio settings. Once again thank you so much
> 
@tqvunguyen Happy to help!
