### ISSUE TITLE
Won't connect

### ISSUE THREAD

**Issue by kwalkington** [toscano/hass-avpro-acmxnn#2]
Installed via HACS.
Restarted.
Integration shows up in integrations.
Typed in IP address of AX-MX-44.  
"Failed to Connect"
I can load the UI in a browser with the IP.
No password.

**Comment by kwalkington** [comment]
AC-MX44-AUHD
--
V1.20

**Comment by toscano** [comment]
Hi @kwalkington , thanks for using the component.

I've seen this once before in defect #1.
 
**TLDR** - we were able to resolve it.

This [link](https://github.com/toscano/hass-avpro-acmxnn/issues/1#issuecomment-2173915680) should take you to the heart of the matter but you may want to read the entire thread. 

Please let me know if this fixes thing for you... or if not please respond to this thread with the response from your matrix to the request... `http://IP_OF_YOUR_MATRIX/do?cmd=status`

-M

**Comment by kwalkington** [comment]
Thanks for helping..
In the browser, I'm getting:
"Sorry, the page you requested was not found."

**Comment by kwalkington** [comment]
When entering "http://IP_OF_YOUR_MATRIX/do?cmd=status"

**Comment by toscano** [comment]
@kwalkington 

It looks like you have a previous generation matrix (see this [link](https://www.bhphotovideo.com/c/replacement_for/1485936-REG/avpro_edge_avp_ac_mx44_auhd_auhd_4x4_hdmi_matrix.html)). It looks like it's not compatible with the web-socket API that this component requires.

Sorry.
-M

**Comment by kwalkington** [comment]
It looks like the same model.

**Comment by toscano** [comment]
They look the same but the newer version supports the Web-socket API.

**Comment by kwalkington** [comment]
Ok. Thanks. I appreciate the help. Do you recommend any comparable matrix that integrates with Home Assistant?On Nov 8, 2024, at 3:14 PM, Michael Toscano ***@***.***> wrote:﻿
They look the same but the newer version supports the Web-socket API.

**Comment by toscano** [comment]
Sorry @kwalkington , this is the only one I have experience with.
